service: vtru-studio-lambda-thumb-video
frameworkVersion: '3'

layers:
    ffmpeg:
        path: layers

provider:
    name: aws
    stage: qa
    runtime: nodejs18.x
    memorySize: 1024
    timeout: 300
    iamRoleStatements:
        - Effect: Allow
          Action:
              - s3:*
          Resource: '*'

custom:
    bucket: vitruveo-studio-${opt:stage, 'qa'}-assets

functions:
    postprocess:
        handler: handler.postprocess
        environment:
            NOTIFY_API_URL: ${param:NOTIFY_API_URL}
        layers:
            - { Ref: FfmpegLambdaLayer }
        events:
            - s3:
                  bucket: ${self:custom.bucket}
                  event: s3:ObjectCreated:*
                  rules:
                      - suffix: mp4
                  existing: true
            - s3:
                  bucket: ${self:custom.bucket}
                  event: s3:ObjectCreated:*
                  rules:
                      - suffix: avi
                  existing: true
            - s3:
                  bucket: ${self:custom.bucket}
                  event: s3:ObjectCreated:*
                  rules:
                      - suffix: mpg
                  existing: true
            - s3:
                  bucket: ${self:custom.bucket}
                  event: s3:ObjectCreated:*
                  rules:
                      - suffix: webm
                  existing: true

    postdelete:
        handler: handler.postdelete
        events:
            - s3:
                  bucket: ${self:custom.bucket}
                  event: s3:ObjectRemoved:*
                  rules:
                      - suffix: mp4
                  existing: true
            - s3:
                  bucket: ${self:custom.bucket}
                  event: s3:ObjectRemoved:*
                  rules:
                      - suffix: avi
                  existing: true
            - s3:
                  bucket: ${self:custom.bucket}
                  event: s3:ObjectRemoved:*
                  rules:
                      - suffix: mpg
                  existing: true
            - s3:
                  bucket: ${self:custom.bucket}
                  event: s3:ObjectRemoved:*
                  rules:
                      - suffix: webm
                  existing: true
